# This tells Netlify how to build your site
[build]
  command = "npm run build"
  publish = "dist"

# This is the rule that makes your page links (React Router) work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200